name: node2vec_ml1m
description: Node2Vec (biased random walks + Skip-gram) on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_binary_tfrecord.yaml
model: 33-node2vec/model.yaml
train: 33-node2vec/trainer.yaml
