name: word2vec_ml1m
description: Word2Vec (Skip-gram with Negative Sampling) on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_binary_tfrecord.yaml
model: 32-word2vec/model.yaml
train: 32-word2vec/trainer.yaml
