task: binary
slim:
  history_field: user_movie_rate_ids
  target_field: movie_id
  embedding_dim: 8
embedding:
  default_emb_size: 8
  fields:
    user_id:
      field_index: 1
      field_type: 1
      dim: 5393
      emb_size: 8
      enabled: true
    movie_id:
      field_index: 101
      field_type: 1
      dim: 3705
      emb_size: 8
      enabled: true
    user_movie_rate_ids:
      field_index: 101
      field_type: 1
      dim: 3705
      emb_size: 8
      enabled: true
