name: mind_ml1m
description: MIND (Multi-Interest Network with Dynamic Routing) on MovieLens 1M TFRecord samples.

data: configs/0-data/ml1m_binary_tfrecord.yaml
model: configs/12-mind/model.yaml
train: configs/12-mind/trainer.yaml
