name: mind_ml1m
description: MIND (Multi-Interest Network with Dynamic Routing) on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_binary_tfrecord.yaml
model: 12-mind/model.yaml
train: 12-mind/trainer.yaml
