name: youtube_dnn_ml1m
description: YouTubeDNN (YouTube Deep Neural Network) on MovieLens 1M multi-class TFRecord samples.

data: configs/0-data/ml1m_multiclass_tfrecord.yaml
model: configs/8-youtube_dnn/model.yaml
train: configs/8-youtube_dnn/trainer.yaml
