name: slim_paper_ml1m
description: SLIM (paper, coordinate descent with fsSLIM) on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_binary_tfrecord.yaml
model: 1-slim_paper/model.yaml
train: 1-slim_paper/trainer.yaml
