name: adatt_ml1m
description: AdaTT (Adaptive Task-to-Task Fusion Network) on MovieLens 1M TFRecord samples.

data: configs/0-data/ml1m_binary_tfrecord.yaml
model: configs/24-adatt/model.yaml
train: configs/24-adatt/trainer.yaml
