name: deepfm_ml1m
description: DeepFM (Deep Factorization Machine with Field Attention) on MovieLens 1M TFRecord samples.

data: configs/0-data/ml1m_binary_tfrecord.yaml
model: configs/4-deepfm/model.yaml
train: configs/4-deepfm/trainer.yaml
