name: xdeepfm_ml1m
description: xDeepFM (eXtreme Deep Factorization Machine with CIN) on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_binary_tfrecord.yaml
model: 5-xdeepfm/model.yaml
train: 5-xdeepfm/trainer.yaml
