name: ncf_ml1m
description: NCF (Neural Collaborative Filtering) on MovieLens 1M TFRecord samples.

data: configs/0-data/ml1m_binary_tfrecord.yaml
model: configs/3-ncf/model.yaml
train: configs/3-ncf/trainer.yaml
