name: mvdnn_ml1m
description: MV-DNN (Multi-View Deep Neural Network) on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_binary_tfrecord.yaml
model: 99-mvdnn/model.yaml
train: 99-mvdnn/trainer.yaml
