name: pepnet_ml1m
description: PEPNet (Parameter Efficient Personalized Network) on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_binary_tfrecord.yaml
model: 23-pepnet/model.yaml
train: 23-pepnet/trainer.yaml
