target_size: 3662
embedding:
  default_emb_dim: 16
  fields:
    user_age:
      f_index: 2
      f_type: 1
      vocab_size: 8
      emb_dim: 16
    user_gender:
      f_index: 3
      f_type: 1
      vocab_size: 3
      emb_dim: 8
    user_occupation:
      f_index: 4
      f_type: 1
      vocab_size: 21
      emb_dim: 16
    user_rate_std:
      f_index: 6
      f_type: 1
      vocab_size: 4
      emb_dim: 32
    user_rate_std_7day:
      f_index: 7
      f_type: 1
      vocab_size: 4
      emb_dim: 32
    user_rate_std_15day:
      f_index: 8
      f_type: 1
      vocab_size: 4
      emb_dim: 32
    user_rate_std_30day:
      f_index: 9
      f_type: 1
      vocab_size: 4
      emb_dim: 32
    user_movie_rate_cnt:
      f_index: 10
      f_type: 1
      vocab_size: 6
      emb_dim: 32
    user_movie_rate_cnt_7day:
      f_index: 11
      f_type: 1
      vocab_size: 6
      emb_dim: 32
    user_movie_rate_cnt_15day:
      f_index: 12
      f_type: 1
      vocab_size: 7
      emb_dim: 32
    user_movie_rate_cnt_30day:
      f_index: 13
      f_type: 1
      vocab_size: 7
      emb_dim: 32
    user_avg_rate:
      f_index: 14
      f_type: 1
      vocab_size: 4
      emb_dim: 32
    user_avg_rate_7day:
      f_index: 15
      f_type: 1
      vocab_size: 4
      emb_dim: 32
    user_avg_rate_15day:
      f_index: 16
      f_type: 1
      vocab_size: 4
      emb_dim: 32
    user_avg_rate_30day:
      f_index: 17
      f_type: 1
      vocab_size: 4
      emb_dim: 32
    user_rate_std_continue:
      f_index: 18
      f_type: 0
      vocab_size: 2
      emb_dim: 32
    user_rate_std_7day_continue:
      f_index: 19
      f_type: 0
      vocab_size: 2
      emb_dim: 32
    user_rate_std_15day_continue:
      f_index: 21
      f_type: 0
      vocab_size: 2
      emb_dim: 32
    user_rate_std_30day_continue:
      f_index: 22
      f_type: 0
      vocab_size: 2
      emb_dim: 32
    user_avg_rate_continue:
      f_index: 23
      f_type: 0
      vocab_size: 2
      emb_dim: 32
    user_avg_rate_7day_continue:
      f_index: 24
      f_type: 0
      vocab_size: 2
      emb_dim: 32
    user_avg_rate_15day_continue:
      f_index: 25
      f_type: 0
      vocab_size: 2
      emb_dim: 32
    user_avg_rate_30day_continue:
      f_index: 26
      f_type: 0
      vocab_size: 2
      emb_dim: 32
    movie_title:
      f_index: 102
      f_type: 1
      vocab_size: 4268
      emb_dim: 32
    movie_genres:
      f_index: 103
      f_type: 1
      vocab_size: 19
      emb_dim: 32
    movie_rate_count:
      f_index: 104
      f_type: 1
      vocab_size: 11
      emb_dim: 32
    movie_avg_rate:
      f_index: 105
      f_type: 1
      vocab_size: 9
      emb_dim: 32
    movie_genre_cnt:
      f_index: 106
      f_type: 1
      vocab_size: 4
      emb_dim: 32
    item_hot_rank:
      f_index: 107
      f_type: 1
      vocab_size: 5
      emb_dim: 32
    movie_publish_year:
      f_index: 108
      f_type: 1
      vocab_size: 6
      emb_dim: 32
    movie_avg_rate_continue:
      f_index: 109
      f_type: 0
      vocab_size: 2
      emb_dim: 32
    context_time_hour:
      f_index: 201
      f_type: 1
      vocab_size: 25
      emb_dim: 16
    context_time_area:
      f_index: 202
      f_type: 1
      vocab_size: 7
      emb_dim: 16
    context_time_week:
      f_index: 203
      f_type: 1
      vocab_size: 8
      emb_dim: 16
    context_is_weekend:
      f_index: 204
      f_type: 1
      vocab_size: 3
      emb_dim: 8
    user_movie_rate:
      f_index: 301
      f_type: 1
      vocab_size: 3569
      emb_dim: 32
    user_movie_rate_1day:
      f_index: 302
      f_type: 1
      vocab_size: 3558
      emb_dim: 32
    user_movie_rate_3day:
      f_index: 303
      f_type: 1
      vocab_size: 3558
      emb_dim: 32
    user_movie_rate_7day:
      f_index: 304
      f_type: 1
      vocab_size: 3558
      emb_dim: 32
    user_movie_rate_15day:
      f_index: 305
      f_type: 1
      vocab_size: 3562
      emb_dim: 32
    user_genres_rate:
      f_index: 306
      f_type: 1
      vocab_size: 19
      emb_dim: 32
    user_genres_rate_1day:
      f_index: 307
      f_type: 1
      vocab_size: 19
      emb_dim: 32
    user_genres_rate_3day:
      f_index: 308
      f_type: 1
      vocab_size: 19
      emb_dim: 32
    user_genres_rate_7day:
      f_index: 309
      f_type: 1
      vocab_size: 19
      emb_dim: 32
    user_genres_rate_15day:
      f_index: 310
      f_type: 1
      vocab_size: 19
      emb_dim: 32
    user_genres_rate_cnts:
      f_index: 312
      f_type: 1
      vocab_size: 19
      emb_dim: 32
    user_genres_rate_cnt_1days:
      f_index: 313
      f_type: 1
      vocab_size: 19
      emb_dim: 32
    user_genres_rate_cnt_3days:
      f_index: 314
      f_type: 1
      vocab_size: 19
      emb_dim: 32
    user_genres_rate_cnt_7days:
      f_index: 315
      f_type: 1
      vocab_size: 19
      emb_dim: 32
    user_genres_rate_cnt_15days:
      f_index: 316
      f_type: 1
      vocab_size: 19
      emb_dim: 32
    user_top3_genres:
      f_index: 317
      f_type: 1
      vocab_size: 19
      emb_dim: 32
    user_watch_same_genre:
      f_index: 351
      f_type: 1
      vocab_size: 3
      emb_dim: 32
    user_watch_same_genre_1day:
      f_index: 352
      f_type: 1
      vocab_size: 3
      emb_dim: 32
    user_watch_same_genre_3day:
      f_index: 353
      f_type: 1
      vocab_size: 3
      emb_dim: 32
    user_watch_same_genre_7day:
      f_index: 354
      f_type: 1
      vocab_size: 3
      emb_dim: 32
    user_watch_same_genre_15day:
      f_index: 355
      f_type: 1
      vocab_size: 3
      emb_dim: 32
    user_same_genre_avg_rate:
      f_index: 356
      f_type: 1
      vocab_size: 6
      emb_dim: 32
    user_same_genre_avg_rate_continue:
      f_index: 357
      f_type: 0
      vocab_size: 2
      emb_dim: 32
attention:
  enabled: false
mlp:
  hidden_dims:
  - 256
  - 128
  activation: relu
  dropout: 0.1
  batch_norm: false
  input_batch_norm: false
