name: gwen_ml1m_binary
description: GwEN rank model on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_binary_tfrecord.yaml
model: 2-gwen_ml1m_binary/model.yaml
train: 2-gwen_ml1m_binary/trainer.yaml
