name: dcnv2_ml1m
description: DCNv2 (Deep & Cross Network V2) on MovieLens 1M TFRecord samples.

data: configs/0-data/ml1m_binary_tfrecord.yaml
model: configs/6-dcnv2/model.yaml
train: configs/6-dcnv2/trainer.yaml
