name: eges_ml1m
description: EGES (Enhanced Graph Embedding with Side Information) on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_binary_tfrecord.yaml
model: 31-eges/model.yaml
train: 31-eges/trainer.yaml
