name: mimn_ml1m
description: MIMN (Multi-channel Interest with Moment Network) on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_binary_tfrecord.yaml
model: 10-mimn/model.yaml
train: 10-mimn/trainer.yaml
