name: sasrec_ml1m
description: SASRec (Self-Attentive Sequential Recommendation) on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_binary_tfrecord.yaml
model: 16-sasrec/model.yaml
train: 16-sasrec/trainer.yaml
