name: gwen_ml1m_multiclass
description: GwEN multi-class classification on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_multiclass_tfrecord.yaml
model: 2-gwen_ml1m_multiclass/model.yaml
train: 2-gwen_ml1m_multiclass/trainer.yaml
