name: deepfm_ml1m
description: DeepFM (Deep Factorization Machine with Field Attention) on MovieLens 1M TFRecord samples.

data: 0-data/ml1m_binary_tfrecord.yaml
model: 5-deepfm/model.yaml
train: 5-deepfm/trainer.yaml
