task: binary
behavior_fields:
- user_movie_rate
- user_movie_rate_1day
- user_movie_rate_3day
- user_movie_rate_7day
- user_movie_rate_15day
- user_genres_rate
- user_genres_rate_1day
- user_genres_rate_3day
- user_genres_rate_7day
- user_genres_rate_15day
target_fields:
- movie_id
- movie_genres
softmax_attn: false
target_merge: mean
interest_extractor:
  num_tables: 4
  num_bits: 4

local_activation_unit:
  hidden_dims:
  - 32
  - 16
  bias:
  - true
  - true
  batch_norm: true
  activation: relu
embedding:
  default_emb_size: 4
  fields:
    user_id:
      field_index: 1
      field_type: 1
      dim: 5393
      emb_size: 4
      enabled: true
    user_age:
      field_index: 2
      field_type: 1
      dim: 8
      emb_size: 4
      enabled: true
    user_gender:
      field_index: 3
      field_type: 1
      dim: 3
      emb_size: 4
      enabled: true
    user_occupation:
      field_index: 4
      field_type: 1
      dim: 21
      emb_size: 4
      enabled: true
    user_rate_std:
      field_index: 6
      field_type: 1
      dim: 4
      emb_size: 4
      enabled: true
    user_rate_std_7day:
      field_index: 7
      field_type: 1
      dim: 4
      emb_size: 4
      enabled: true
    user_rate_std_15day:
      field_index: 8
      field_type: 1
      dim: 4
      emb_size: 4
      enabled: true
    user_rate_std_30day:
      field_index: 9
      field_type: 1
      dim: 4
      emb_size: 4
      enabled: true
    user_movie_rate_cnt:
      field_index: 10
      field_type: 1
      dim: 7
      emb_size: 4
      enabled: true
    user_movie_rate_cnt_7day:
      field_index: 11
      field_type: 1
      dim: 7
      emb_size: 4
      enabled: true
    user_movie_rate_cnt_15day:
      field_index: 12
      field_type: 1
      dim: 7
      emb_size: 4
      enabled: true
    user_movie_rate_cnt_30day:
      field_index: 13
      field_type: 1
      dim: 7
      emb_size: 4
      enabled: true
    user_avg_rate:
      field_index: 14
      field_type: 1
      dim: 4
      emb_size: 4
      enabled: true
    user_avg_rate_7day:
      field_index: 15
      field_type: 1
      dim: 4
      emb_size: 4
      enabled: true
    user_avg_rate_15day:
      field_index: 16
      field_type: 1
      dim: 4
      emb_size: 4
      enabled: true
    user_avg_rate_30day:
      field_index: 17
      field_type: 1
      dim: 4
      emb_size: 4
      enabled: true
    user_rate_std_continue:
      field_index: 18
      field_type: 0
      dim: 2
      concat_type: direct
      emb_size: 4
      enabled: true
    user_rate_std_7day_continue:
      field_index: 19
      field_type: 0
      dim: 2
      concat_type: direct
      emb_size: 4
      enabled: true
    user_rate_std_15day_continue:
      field_index: 21
      field_type: 0
      dim: 2
      concat_type: direct
      emb_size: 4
      enabled: true
    user_rate_std_30day_continue:
      field_index: 22
      field_type: 0
      dim: 2
      concat_type: direct
      emb_size: 4
      enabled: true
    user_avg_rate_continue:
      field_index: 23
      field_type: 0
      dim: 2
      concat_type: direct
      emb_size: 4
      enabled: true
    user_avg_rate_7day_continue:
      field_index: 24
      field_type: 0
      dim: 2
      concat_type: direct
      emb_size: 4
      enabled: true
    user_avg_rate_15day_continue:
      field_index: 25
      field_type: 0
      dim: 2
      concat_type: direct
      emb_size: 4
      enabled: true
    user_avg_rate_30day_continue:
      field_index: 26
      field_type: 0
      dim: 2
      concat_type: direct
      emb_size: 4
      enabled: true
    movie_id:
      field_index: 101
      field_type: 1
      dim: 3579
      emb_size: 16
      enabled: true
    user_movie_rate:
      field_index: 101
      field_type: 1
      dim: 3579
      emb_size: 16
      enabled: true
    user_movie_rate_15day:
      field_index: 101
      field_type: 1
      dim: 3579
      emb_size: 16
      enabled: true
    user_movie_rate_1day:
      field_index: 101
      field_type: 1
      dim: 3579
      emb_size: 16
      enabled: true
    user_movie_rate_3day:
      field_index: 101
      field_type: 1
      dim: 3579
      emb_size: 16
      enabled: true
    user_movie_rate_7day:
      field_index: 101
      field_type: 1
      dim: 3579
      emb_size: 16
      enabled: true
    movie_title:
      field_index: 102
      field_type: 1
      dim: 4524
      emb_size: 4
      enabled: true
    movie_genres:
      field_index: 103
      field_type: 1
      dim: 19
      emb_size: 16
      enabled: true
    user_genres_rate:
      field_index: 103
      field_type: 1
      dim: 19
      emb_size: 16
      enabled: true
    user_genres_rate_15day:
      field_index: 103
      field_type: 1
      dim: 19
      emb_size: 16
      enabled: true
    user_genres_rate_1day:
      field_index: 103
      field_type: 1
      dim: 19
      emb_size: 16
      enabled: true
    user_genres_rate_3day:
      field_index: 103
      field_type: 1
      dim: 19
      emb_size: 16
      enabled: true
    user_genres_rate_7day:
      field_index: 103
      field_type: 1
      dim: 19
      emb_size: 16
      enabled: true
    movie_rate_count:
      field_index: 104
      field_type: 1
      dim: 11
      emb_size: 4
      enabled: true
    movie_avg_rate:
      field_index: 105
      field_type: 1
      dim: 9
      emb_size: 4
      enabled: true
    movie_genre_cnt:
      field_index: 106
      field_type: 1
      dim: 4
      emb_size: 4
      enabled: true
    item_hot_rank:
      field_index: 107
      field_type: 1
      dim: 5
      emb_size: 4
      enabled: true
    movie_publish_year:
      field_index: 108
      field_type: 1
      dim: 6
      emb_size: 4
      enabled: true
    movie_avg_rate_continue:
      field_index: 109
      field_type: 0
      dim: 2
      concat_type: direct
      emb_size: 4
      enabled: true
    context_time_hour:
      field_index: 201
      field_type: 1
      dim: 25
      emb_size: 4
      enabled: true
    context_time_area:
      field_index: 202
      field_type: 1
      dim: 7
      emb_size: 4
      enabled: true
    context_time_week:
      field_index: 203
      field_type: 1
      dim: 8
      emb_size: 4
      enabled: true
    context_is_weekend:
      field_index: 204
      field_type: 1
      dim: 3
      emb_size: 4
      enabled: true
    user_genres_rate_cnts:
      field_index: 312
      field_type: 1
      dim: 19
      emb_size: 4
      enabled: true
    user_genres_rate_cnt_1days:
      field_index: 313
      field_type: 1
      dim: 19
      emb_size: 4
      enabled: true
    user_genres_rate_cnt_3days:
      field_index: 314
      field_type: 1
      dim: 19
      emb_size: 4
      enabled: true
    user_genres_rate_cnt_7days:
      field_index: 315
      field_type: 1
      dim: 19
      emb_size: 4
      enabled: true
    user_genres_rate_cnt_15days:
      field_index: 316
      field_type: 1
      dim: 19
      emb_size: 4
      enabled: true
    user_top3_genres:
      field_index: 317
      field_type: 1
      dim: 19
      emb_size: 4
      enabled: true
    user_watch_same_genre:
      field_index: 351
      field_type: 1
      dim: 3
      emb_size: 4
      enabled: true
    user_watch_same_genre_1day:
      field_index: 352
      field_type: 1
      dim: 3
      emb_size: 4
      enabled: true
    user_watch_same_genre_3day:
      field_index: 353
      field_type: 1
      dim: 3
      emb_size: 4
      enabled: true
    user_watch_same_genre_7day:
      field_index: 354
      field_type: 1
      dim: 3
      emb_size: 4
      enabled: true
    user_watch_same_genre_15day:
      field_index: 355
      field_type: 1
      dim: 3
      emb_size: 4
      enabled: true
    user_same_genre_avg_rate:
      field_index: 356
      field_type: 1
      dim: 6
      emb_size: 4
      enabled: true
    user_same_genre_avg_rate_continue:
      field_index: 357
      field_type: 0
      dim: 2
      concat_type: direct
      emb_size: 4
      enabled: true

mlp:
  hidden_dims:
  - 256
  - 128
  activation: relu
  dropout: 0.1
  batch_norm: true
  input_batch_norm: true
field_attention:
  enabled: false
